### 参考

- [Deep Learning基礎講座演習（松尾研）](https://matsuolabdeeplearning-vochicong.notebooks.azure.com/nb/notebooks/lecture_chap02_exercise_master.ipynb)


In [4]:
import numpy as np

### Softmax function, or normalized exponential function
\begin{align}
soft\max&:\mathbb{R}^K \to (0,1)^K \\
soft\max& (\mathbf {z} )_{j}={\frac {e^{z_{j}}}{\sum _{k=1}^{K}e^{z_{k}}}}
\operatorname{for} j = 1, …, K.
\end{align}

### 双曲線余弦関数 (hyperbolic cosine; ハイパボリックコサイン)

$$
\tanh:\mathbb{R} \to (-1,1) \\
\tanh x={e^{x}-e^{-x} \over e^{x}+e^{-x}}
$$

- mathwords [tanhの意味、グラフ、微分、積分](https://mathwords.net/haipaborictan)

### Sigmoid

$$ {\displaystyle \sigma _{a}(x)={\frac {1}{1+e^{-ax}}}={\frac {\tanh(ax/2)+1}{2}}}  $$

### Dot product

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method.

In [2]:
A = np.arange(9.0).reshape((3, 3))
A

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [3]:
x = np.arange(3.0)
x

array([ 0.,  1.,  2.])

#### Dot product $ Ax $:

In [4]:
A.dot(x)

array([  5.,  14.,  23.])

#### Elementwise product

In [5]:
A*x

array([[  0.,   1.,   4.],
       [  0.,   4.,  10.],
       [  0.,   7.,  16.]])

In [8]:
np.zeros([2,3]) #np.zeros(2,3) ではない！

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [19]:
np.append(x, 7)

array([ 3.,  4.,  5.,  7.])

In [20]:
list = ["A", "B", "C"]
list.append("D")
list

['A', 'B', 'C', 'D']

In [21]:
np.append(x, [7,8])

array([ 3.,  4.,  5.,  7.,  8.])

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b.T), axis=1)

In [23]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
c.shape

(3, 2)

In [27]:
d

array([[1, 2, 5],
       [3, 4, 6]])

In [28]:
d.shape

(2, 3)

# Hash

In [2]:
h = {"a": 1, "b": 2, "c": 3}

In [4]:
h

{'a': 1, 'b': 2, 'c': 3}

In [5]:
h["a"]

1

In [7]:
[h[k] for k in ["a", "b"]]

[1, 2]

In [2]:
h=[10,3,40]

### 最大、平均

In [5]:
np.max(h)

40

In [7]:
np.average(h)

17.666666666666668